name: antaa
version: 0.1.0.0
github: "githubuser/antaa"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2022 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/antaa#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - megaparsec

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - DerivingVia
  - DeriveAnyClass
  - ImportQualifiedPost
  - DuplicateRecordFields
  - OverloadedRecordDot
  - LambdaCase
  - Strict
  - StrictData
  - PatternSynonyms
  - ViewPatterns

library:
  source-dirs: src

executables:
  antaa-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - antaa

tests:
  antaa-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - antaa
